/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MilestoneVault {
  export type MilestoneStruct = {
    description: string;
    percentage: BigNumberish;
    status: BigNumberish;
  };

  export type MilestoneStructOutput = [
    description: string,
    percentage: bigint,
    status: bigint
  ] & { description: string; percentage: bigint; status: bigint };

  export type RequestStruct = {
    id: BigNumberish;
    reqType: BigNumberish;
    milestoneIndex: BigNumberish;
    amount: BigNumberish;
    reason: string;
    status: BigNumberish;
  };

  export type RequestStructOutput = [
    id: bigint,
    reqType: bigint,
    milestoneIndex: bigint,
    amount: bigint,
    reason: string,
    status: bigint
  ] & {
    id: bigint;
    reqType: bigint;
    milestoneIndex: bigint;
    amount: bigint;
    reason: string;
    status: bigint;
  };
}

export interface MilestoneVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAgreement"
      | "approveRequest"
      | "arbiter"
      | "builder"
      | "deposit"
      | "getMilestoneCount"
      | "getMilestones"
      | "getRequestCount"
      | "getRequests"
      | "investor"
      | "milestones"
      | "raiseDispute"
      | "rejectRequest"
      | "remainingLocked"
      | "requestAdHoc"
      | "requestMilestonePayout"
      | "requests"
      | "resolveDispute"
      | "status"
      | "totalDeposited"
      | "totalReleased"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementAccepted"
      | "Deposited"
      | "DisputeRaised"
      | "DisputeResolved"
      | "RequestApproved"
      | "RequestCreated"
      | "RequestRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAgreement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "arbiter", values?: undefined): string;
  encodeFunctionData(functionFragment: "builder", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMilestoneCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestones",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequests",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "investor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAdHoc",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMilestonePayout",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbiter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "builder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "investor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAdHoc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMilestonePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
}

export namespace AgreementAcceptedEvent {
  export type InputTuple = [builder: AddressLike];
  export type OutputTuple = [builder: string];
  export interface OutputObject {
    builder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [investor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investor: string, amount: bigint];
  export interface OutputObject {
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    releasedToBuilder: boolean
  ];
  export type OutputTuple = [requestId: bigint, releasedToBuilder: boolean];
  export interface OutputObject {
    requestId: bigint;
    releasedToBuilder: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [requestId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [requestId: bigint, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    reqType: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    reqType: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    reqType: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRejectedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MilestoneVault extends BaseContract {
  connect(runner?: ContractRunner | null): MilestoneVault;
  waitForDeployment(): Promise<this>;

  interface: MilestoneVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAgreement: TypedContractMethod<[], [void], "nonpayable">;

  approveRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  arbiter: TypedContractMethod<[], [string], "view">;

  builder: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  getMilestoneCount: TypedContractMethod<[], [bigint], "view">;

  getMilestones: TypedContractMethod<
    [],
    [MilestoneVault.MilestoneStructOutput[]],
    "view"
  >;

  getRequestCount: TypedContractMethod<[], [bigint], "view">;

  getRequests: TypedContractMethod<
    [],
    [MilestoneVault.RequestStructOutput[]],
    "view"
  >;

  investor: TypedContractMethod<[], [string], "view">;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        description: string;
        percentage: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  raiseDispute: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  remainingLocked: TypedContractMethod<[], [bigint], "view">;

  requestAdHoc: TypedContractMethod<
    [amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  requestMilestonePayout: TypedContractMethod<
    [milestoneIndex: BigNumberish, evidenceLink: string],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        id: bigint;
        reqType: bigint;
        milestoneIndex: bigint;
        amount: bigint;
        reason: string;
        status: bigint;
      }
    ],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [requestId: BigNumberish, releaseToBuilder: boolean],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[], [bigint], "view">;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAgreement"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "arbiter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "builder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getMilestoneCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMilestones"
  ): TypedContractMethod<[], [MilestoneVault.MilestoneStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequests"
  ): TypedContractMethod<[], [MilestoneVault.RequestStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "investor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        description: string;
        percentage: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remainingLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestAdHoc"
  ): TypedContractMethod<
    [amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMilestonePayout"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish, evidenceLink: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint] & {
        id: bigint;
        reqType: bigint;
        milestoneIndex: bigint;
        amount: bigint;
        reason: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [requestId: BigNumberish, releaseToBuilder: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AgreementAccepted"
  ): TypedContractEvent<
    AgreementAcceptedEvent.InputTuple,
    AgreementAcceptedEvent.OutputTuple,
    AgreementAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreated"
  ): TypedContractEvent<
    RequestCreatedEvent.InputTuple,
    RequestCreatedEvent.OutputTuple,
    RequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRejected"
  ): TypedContractEvent<
    RequestRejectedEvent.InputTuple,
    RequestRejectedEvent.OutputTuple,
    RequestRejectedEvent.OutputObject
  >;

  filters: {
    "AgreementAccepted(address)": TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;
    AgreementAccepted: TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "DisputeRaised(uint256)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "RequestApproved(uint256,uint256)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestCreated(uint256,uint8,uint256)": TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
    RequestCreated: TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;

    "RequestRejected(uint256)": TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;
    RequestRejected: TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;
  };
}
