/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MilestoneVaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allVaults"
      | "arbiter"
      | "createAgreement"
      | "getAllVaults"
      | "getBuilderVaults"
      | "getInvestorVaults"
      | "getVaultCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "arbiter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [AddressLike, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuilderVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "arbiter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuilderVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultCount",
    data: BytesLike
  ): Result;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    investor: AddressLike,
    builder: AddressLike
  ];
  export type OutputTuple = [vault: string, investor: string, builder: string];
  export interface OutputObject {
    vault: string;
    investor: string;
    builder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MilestoneVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MilestoneVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: MilestoneVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  arbiter: TypedContractMethod<[], [string], "view">;

  createAgreement: TypedContractMethod<
    [
      _builder: AddressLike,
      _milestoneDescriptions: string[],
      _milestonePercentages: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;

  getAllVaults: TypedContractMethod<[], [string[]], "view">;

  getBuilderVaults: TypedContractMethod<
    [builder_: AddressLike],
    [string[]],
    "view"
  >;

  getInvestorVaults: TypedContractMethod<
    [investor: AddressLike],
    [string[]],
    "view"
  >;

  getVaultCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "arbiter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      _builder: AddressLike,
      _milestoneDescriptions: string[],
      _milestonePercentages: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBuilderVaults"
  ): TypedContractMethod<[builder_: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getInvestorVaults"
  ): TypedContractMethod<[investor: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "VaultCreated(address,address,address)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
